version: '3'

services:
  teamspeak:
    image: reverie89/teamspeak
    container_name: teamspeak
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - "/opt/docker/teamspeak:/opt/teamspeak"